### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by Hasssan-Ramadan**
'single' -> 'song'

### CODE REVIEW

**Comment by iliakan** [comment]
Is "single" really difficult to understand here and should be replaced?

**Comment by Hasssan-Ramadan** [comment]
I'm not an English native speaker, I didn't know that "single" has the same meaning as "song". I thought it is a typo, so I opened this PR. I'm sorry for that.

**Comment by iliakan** [comment]
I think, it's a valid point. I'd probably merge it.

**Comment by iliakan** [comment]
Not only you may have trouble understanding this word.

**Pull request closed without merging**
