### PR TITLE
Modify syntax error on task section

### PR DESCRIPTION
**Pull request by Violet-Bora-Lee**

### CODE REVIEW

**Comment by iliakan** [comment]
What was wrong?

**Comment by Violet-Bora-Lee** [comment]
I should've uploaded the image but I couldn't. You can check the broken syntax on the task section of this article.
http://javascript.info/comparison

**Comment by Violet-Bora-Lee** [comment]
KakaoTalk_20190709_001152282

**Comment by iliakan** [comment]
Sorry, I may be just not getting something. Can't see what's wrong :(

**Comment by Violet-Bora-Lee** [comment]
In order to highlight something in the code box, you are using `*!*text to highlight*/!*` not  `"\n text to highlight \n"`. Isn't it your intention that comparing `null` and `0` in the task? I may be over-thinking.

**Comment by iliakan** [comment]
The intention is to compare `null` against the given string.

**Comment by Violet-Bora-Lee** [comment]
Oh i see now. Ill close the pr

**Pull request closed without merging**
