### PR TITLE
mdn links

### PR DESCRIPTION
**Pull request by joaquinelio**
@iliakan 
How commited (!) are you with mdn: link format?  And  Mozilla its categories?
It's really handy for translations. And fewer errors.

There are a few more, 
but these are in the our untranslated area and I tested every single one on my local EN server 
mdn:/api /JavaScript /http

### CODE REVIEW

**Comment by iliakan** [comment]
Yeah, that's better. Can I merge this?
Did you test that links are correct?

**Comment by joaquinelio** [comment]
Yes
They all checked. I did it in my local english server. All of them opened MDN nicelly.

Every single one, thats why I didnt replace them all, just lazy =)

**Comment by iliakan** [comment]
Cool 🦕

**Comment by joaquinelio** [comment]
Nice! I'll sync.

You want to know, last bot sync PR is only easy 33 files (from hundreds) REAL changes (added Confucio's cite source? Really??? 😆 ok, it's fair)
Didnt do it yet, some mess with line numbers. easier to fix it locally.

**Comment by iliakan** [comment]
You know, Confucio is important for some people 是的是的.

**Comment by MuhammedZakir** [comment]
How is `mdn:` in links resolved? Apologies if this is something obvious! :-)

**Comment by iliakan** [comment]
```js
 if (href.startsWith('mdn:')) {
            let parts = href.slice(4).split('/');

            let locale = lang == 'en' ? 'en-US' : lang;

            let prefix = `https://developer.mozilla.org/${locale}/docs/Web`;

            if (parts[0] == 'js') {
              prefix += '/JavaScript/Reference/Global_Objects/';
            } else if (parts[0] == 'api') {
              prefix += '/API/';
            } else {
              prefix += '/';
            }

            parts.shift();
            href = prefix + parts.join('/');

            tokenUtils.attrReplace(inlineToken, 'href', href);
          }
```

**Comment by MuhammedZakir** [comment]
Thanks! :-) I couldn't find it in javascript-tutorial/server. Only now did I remember about javascript-tutorial/engine repo and found it in https://github.com/javascript-tutorial/engine/blob/master/markit/plugins/resolveMdnSrc.js.

**Pull request merged**
