### PR TITLE
👾 smth

### PR DESCRIPTION
**Pull request by Rnbsov**
What about add it to the article ?

 Screenshot_4

### CODE REVIEW

**Comment by joaquinelio** [comment]
if so,
check firefox too,
I think it was the first with those nice tools - I never tried

**Comment by joaquinelio** [comment]
if so,
check firefox too,
I think it was the first with those nice tools - I never tried

**Comment by Rnbsov** [comment]
Yes, this function is there.

I can even assume that she appeared there even earlier than in chrome

**Comment by Rnbsov** [comment]
I can't check if it's in safari

So it makes sense to add information like:

> If you use Chrome, Firefox (or any other chromium based browser) except Safari. You can try it right in the developer tools dashboard:

**Comment by joaquinelio** [comment]
ok!

about safari, we could ask here in this pr

I bet this ends in a more generic statement
"... main browsers dev tools"

**Comment by Rnbsov** [comment]
> I bet this ends in a more generic statement "... main browsers dev tools"

Yeah, me too

**Comment by iliakan** [comment]
Can you please change the text, make it more generic ("most browsers") and add hints how to reach this panel instead of a screenshot?

**Comment by Rnbsov** [comment]
I left the screenshots unchanged, I think then need to make svgs out of them

Perhaps some adjustments in the text are still needed

**Pull request closed without merging**
