### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by hrodward**
Grammar suggestions

### CODE REVIEW

**Comment by iliakan** [comment]
Maybe "That can lead to interesting consequences when **the** `prototype` property is changed after the object is created." ?

**Comment by hrodward** [comment]
Yep, 'the' is better

**Comment by paroche** [comment]
Agreed. "the prototype property". There's only one (for a given class).

**Comment by paroche** [comment]
However, in the same patch:

_2. Most classes do not have `Symbol.hasInstance`. In that case, the standard logic is used: `obj instanceOf Class` checks whether `Class.prototype` equals to one of prototypes in the `obj` prototype chain.
2. Most classes do not have `Symbol.hasInstance`. In that case, the standard logic is used: `obj instanceOf Class` checks whether `Class.prototype` equals to any prototype in the `obj` prototype chain."_

Both are wrong. It should be "is equal to any prototype", **"is equal to one of the prototypes"**, "equals any prototype", or "equals one of the prototypes". Never "equals to". I would somewhat favor the one I put in bold.

**Comment by iliakan** [comment]
@hrodward will you update the patch if the suggestion is acceptable?

**Comment by hrodward** [comment]
> @hrodward will you update the patch if the suggestion is acceptable?

Done!

**Comment by lex111** [comment]
@hrodward thanks!

**Pull request merged**
