### PR TITLE
Comma place

### PR DESCRIPTION
**Pull request by joaquinelio**
JUST a suggestion.  
I'm not sure about the correct use of the colon either.
The "correction" may be trivial (even wrong) for English. 
I HAD to do this change in the insanely long resulting sentence in Spanish. I asked Fundéu (Spanish academy) and things are more clear now.

Wrong about being wrong about being wrong.
I was studying
https://owl.purdue.edu/owl/general_writing/punctuation/commas/extended_rules_for_commas.html
Rules are different from Spanish,  not THAT different.  
So the suggestion. Again, it may be wrong.

### CODE REVIEW

**Comment by iliakan** [comment]
Semicolon shouldn't be there.

**Comment by joaquinelio** [comment]
@iliakan It's OK you closed it. I'll stop doing comma suggestions, its not my language.

just a clarification, there is no semicolon. 
I put a colon to show the options shallow/deep (I saw you using it in other places) 
And a comma position, I thought it was in a wrong place.
Here it is not important, but in Spanish it's easy to loose track of thinking.

**Comment by iliakan** [comment]
I'm quite sure there should be colon there, sorry.

**Comment by iliakan** [comment]
We do have typos, just not here. Thanks!

**Comment by joaquinelio** [comment]
...
...oh,
you dont mean colon but comma I guess...


> I'm quite sure there should be colon there, sorry.

> Semicolon shouldn't be there.

**Pull request closed without merging**
