### PR TITLE
TRUE point

### PR DESCRIPTION
**Pull request by joaquinelio**
🤣🤣🤣🤣🤣🤣🤣🤣
 
The TRUE point is: 
dont distract the student with hegelian stuff

### CODE REVIEW

**Comment by joaquinelio** [comment]
ok, 
just a joke, you may close this 
Im happy my diabetic sister just survived covid

**Comment by iliakan** [comment]
So happy for you and your sister! 🥳 🦩 🦩 🦩

**Comment by joaquinelio** [comment]
> So happy for you and your sister! 🥳 🦩 🦩 🦩

not a minor thing, (half of my neighbors are inected)
my sis is 50++, obese, diabetic and hipertensve ❤️

**Comment by iliakan** [comment]
Yes, guess her immune system proved to be covid-resistant 💪

**Comment by iliakan** [comment]
Most of my friends had Covid. Get vaccinated if you can.

**Pull request closed without merging**
