### PR TITLE
Address some possible issues in 1.2.11

### PR DESCRIPTION
**Pull request by vsemozhetbyt**
1. Fix some typos.
2. Replace `==` with `===` in a task when it is appropriate to make reader accustomed to good practice.
3. ~Fix some metrics in SVG that caused ugly effect in dark browser mode.~

### CODE REVIEW

**Comment by iliakan** [comment]
What did you fix in SVGs? We use Sketch as the editor, and SVGs are auto-exported, so I'd better fix it there.

**Comment by vsemozhetbyt** [comment]
I will be able to tell a bit later. Some text was out of colored boxes in dark mode, so I may decrease font size and change coordinates.

**Comment by vsemozhetbyt** [comment]
Here is the screenshot  of current svg from my phone, so I think I've changed the ECMASript block.
Screenshot_2020-09-22-15-09-15-020_com android chrome

**Comment by iliakan** [comment]
It seems, you changed another svg: ifelse_task.svg

**Comment by vsemozhetbyt** [comment]
Sorry, wrong PR) This I've changed too.

Here, "TheMaster" may be the issue. 
Screenshot_2020-09-22-15-31-49-455_com android chrome

**Comment by vsemozhetbyt** [comment]
Sorry for the mess, trying to answer from the subway.

**Comment by vsemozhetbyt** [comment]
Should I exclude svg from this PR?
(Sorry, it seems I heve not changed  `1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg` in the previous PR, so maybe it also needs your attention because of "ECMASript" block issue).

**Comment by iliakan** [comment]
Please change it in the sketch instead

**Comment by iliakan** [comment]
Please change it in the sketch instead

**Comment by iliakan** [comment]
Or maybe better just don’t touch messages at all. Anyway will need a total revision of all svgs for the  dark mode

**Comment by vsemozhetbyt** [comment]
SVG excluded.

**Comment by iliakan** [comment]
Thanks!

**Pull request merged**
