### PR TITLE
the dom specs is now one

### PR DESCRIPTION
**Pull request by mohamedsaad4**
W3C and the WHATWG have just signed an agreement to collaborate on the development of a single version of the HTML and DOM specifications.

### CODE REVIEW

**Comment by iliakan** [comment]
Yeah, so W3C links should disappear, right?

**Comment by iliakan** [comment]
Looks like W3C gave everything to WHATWG

**Comment by iliakan** [comment]
I changed the article, take a look.

**Comment by mohamedsaad4** [comment]
Yeah, they will work together in WHATWG repositories.

**Pull request closed without merging**
