### PR TITLE
update todo.md

### PR DESCRIPTION
**Pull request by Violet-Bora-Lee**
- Optional Chaining
- Nullish Coalescing Operator

### CODE REVIEW

**Comment by iliakan** [comment]
I'm returning to improving the tutorial and will add these ASAP!

**Comment by Violet-Bora-Lee** [comment]
Cool!!! Cant wait to share valuable information with Korean fans of you :)

**Comment by iliakan** [comment]
I'm thinking of ways to fundamentally improve the tutorial. Make it a better learning experience. 

Would be interested to hear the ideas, if got any.

**Comment by Violet-Bora-Lee** [comment]
Okay

I love this series so i link the articles on the the comments section with
short explanations

Hope there would be more visualized resources

**Comment by iliakan** [comment]
Like what? Videos?

**Comment by Violet-Bora-Lee** [comment]
https://dev.to/lydiahallie/javascript-visualized-event-loop-3dif

Ah i forgot to add link

**Comment by iliakan** [comment]
Maybe a better learning framework? For people to exercise, share results, help each other.

**Comment by Violet-Bora-Lee** [comment]
Then, it's better to look around Exercism.io or freecodecamp

**Pull request closed without merging**
