### PR TITLE
It can be more clear to read

### PR DESCRIPTION
**Pull request by lumosmind**
nested function call is make this snippet hard to understand. And array destructuring is not mentioned yet. So it can be hard for beginners.

### CODE REVIEW

**Comment by joaquinelio** [comment]
mm...
Agreed it may be too early, but the chaining is a point

**Comment by lumosmind** [comment]
> mm...
> Agreed it may be too early for a beginner, but here the chaining is a point too.

chaining and nesting different things. Chaining is protected if it is the point.

**Comment by joaquinelio** [comment]
ouch! right. 
I meant the line below
"...We can make powerful chains of transforms this way. "

maybe both? 

...your code 
add "better yet"
...original code
so "...We can make powerful chains of transforms this way. " makes sense. I like being introduced to this here.

**Comment by iliakan** [comment]
There are detailed explanations, the reader may need to wrap their head about it, but that's the point.

**Pull request closed without merging**
