### PR TITLE
Fix some words to better convey the actual meaning.

### PR DESCRIPTION
**Pull request by sleepyfurious**
The rationale of the fixes is described in commit messages.

### CODE REVIEW

**Comment by iliakan** [comment]
Merged except 1-js/04-object-basics/02-garbage-collection/article.md

**Comment by sleepyfurious** [comment]
@iliakan I would like to discuss about the exception of 1-js/04-object-basics/02-garbage-collection/article.md. I can't really get why the original sentence is making sense. Here is the original:
> ...And so on until there are unvisited references (reachable from the roots).

Can you provide any alternative explanation around this sentence?

**Comment by iliakan** [comment]
It visits references until there exist unvisited ones (and reachable from the roots).

What should I fix to make this clear?

**Comment by sleepyfurious** [comment]
Does "There exist unvisited ones" intentionally mean "There are ones that have never been visited before"?

**Comment by iliakan** [comment]
"never visited before during the current garbage collection process"

**Comment by sleepyfurious** [comment]
So, the unvisited ones are those meant to be removed. Is this right?

**Comment by iliakan** [comment]
The algorithm recursively visits all it can, starting from the roots. 

What's not visited after that => is removed.

**Comment by iliakan** [comment]
Please suggest changes if you feel they are neccessary.

**Comment by sleepyfurious** [comment]
The ambiguity of "unvisited references" is the two possible meanings between:
> "the reachable from the root but still unvisited ones"

and
> "the unreachable from the root ones". 

The second is what we mean. The first is surely not making any sense, but a reader can easily struggle with it that way because it is tempting to refer to what is said before (which is unvisited one during traversing in this case), not what is after (the references that are unreachable from the root).

I suggest:
> …And so on until every reachable (from the roots) references are visited.

**Pull request closed without merging**
