### PR TITLE
Grammar issues fix

### PR DESCRIPTION
**Pull request by sudhirkumarojhaa**
Made some changes to make it more correct.

### CODE REVIEW

**Comment by iliakan** [comment]
Looks wrong to me, but let @paroche decide.

**Comment by iliakan** [comment]
Thanks!

**Comment by iliakan** [comment]
@paroche Please review =)
"each one equipped with its own bells and whistles." better than "each one with its own bells and whistles." ?

**Comment by paroche** [comment]
I think it's better without "equipped". Could even leave out "one", as below:

There exist many frameworks and development methodologies to build them, each with its own bells and whistles. Usually, special CSS classes and conventions are used to provide "component feel" -- CSS scoping and DOM encapsulation.

There is a slight awkwardness about the way it reads, though. Could perhaps rephrase:
"..., and each one has its own bells and whistles."

**Comment by iliakan** [comment]
Thank you! Changed the file.

**Pull request merged**
