### PR TITLE
'Code editors' tweaks following plain language guidelines

### PR DESCRIPTION
**Pull request by p2635**
My third PR in relation to https://github.com/javascript-tutorial/en.javascript.info/issues/3335, please let me know your thoughts.

I'm not 100% happy with this because the recommended editors should be a table instead of a list. I also understand why the part about 'Visual Studio' code is excluded from the bullet list. It could confuse beginners if they saw VS, VS code and VS community in the same list. I'm not sure how to tackle that.

Note: I'm quite new to contributing on GitHub, so if there is something I can improve on, let me know:

1. Communication skills
2. How I create commits
3. How I name branches
4. How I create PRs

### CODE REVIEW

**Comment by joaquinelio** [comment]
please don't

more than ok if you improve legibility of specific lines,

but this kind of rewriting put a lot of pressure on we maintainers
when we merge from English

**Comment by iliakan** [comment]
Many modifications seem to be excessive.

Maybe I'm just not getting something, @p2635 why did you replace "a lot of" with "many"?

**Comment by iliakan** [comment]
Please keep in mind: not only maintainers need to carefully review all your changes, but translators to other languages will see them as well.

Don't rephrase just because you can. There must be a reason.

**Comment by p2635** [comment]
> Don't rephrase just because you can. There must be a reason.

Please accept my apologies first of all, I know you must seem shocked and I admit that the changes are big. My reason is not to rewrite the whole thing, I tried to write this in #3335 but I have two goals:

1. To optimise the word count (less wordy) - I hope that answers the question about 'a lot of' vs 'many' as well.
2. Improve readability (some things could be better formatted to a list).

I was not aiming to change the overall meaning of the tutorial in any way.  What I missed is that these changes need to be carefully reviewed by translators. I am passionate about editing, but I think my intentions are not in the right place. I feel bad for putting this effort in, feel free to close all the issues and PRs if this is not useful.

**Comment by p2635** [comment]
Closing this because of the lack of interest and I don't think I'm going to revisit this.

**Pull request closed without merging**
