### PR TITLE
Remove Visual Studio Code from IDE

### PR DESCRIPTION
**Pull request by Tchoupinax**
Hello, 

I disagree to call Visual Studio Code as an IDE. As i understand IDE versus text editor and as i have listened around me, VSCode is just a very good text editor, with many good plugins, like Atom, Sublime Text or Brackets.

According me, there are all text editor. IDE are Visual Studio, PHPStorm, Xcode...

We can speak about how change this text, I briefly change it.

Regards,

### CODE REVIEW

**Comment by iliakan** [comment]
I'd request more input on that ;)

**Comment by iliakan** [comment]
Quite probably you're right, I'm not VS Code user though.

**Comment by Ghost-017** [comment]
Text editors open quickly. IDE's take a while to open. VS code opens quickly.

**Comment by iliakan** [comment]
IDEs allow project-wide features, like autocompletion.

VS Code allows project-wide autocompletion, jumping to declarations?

**Comment by cpxPratik** [comment]
VS Code comes into gray area with supporting many features that an IDE usually have such as in debugging, refactoring etc. but it is still source code editor at its core, not full-blown IDE. 
The main issue that i have with PR diff is, It says Visual Studio explicitly windows-only, but Visual studio is also available on macOS though not the same software. So it cannot be said as windows-only.

**Comment by dagolinuxoid** [comment]
'Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS.' So technically yeah - VS Code is defined as a Source Code Editor and not an IDE. At the other hand the line between text editor and IDE  becomes more and more blur nowadays so I think it's not that crucial.

**Comment by AngusMacrae** [comment]
I agree VSCode blurs the line between the two, but if we have to classify it as one or the other, I'd definitely still put it in the "editor" category rather than IDE.

**Comment by iliakan** [comment]
Well, not sure if it matters at all =)

**Pull request closed without merging**
