### PR TITLE
redundant "use case"

### PR DESCRIPTION
**Pull request by joaquinelio**
WIP ? What's wrong with it? Something new?

I just reviewed the translated article!!!!
give us a break

ok, just to report a redundancy, keep in mind in the new version.

### CODE REVIEW

**Comment by joaquinelio** [comment]
Just in case. You know I'm just kidding, dont you?

It's just a fresh article to add -redundancy fixed-...
Being obsolete before born...
Well... I suppose it's the price.  Always up to date is what attracted me in the first case.

**Comment by iliakan** [comment]
Frankly, I wasn't sure why you changed that, but the change wasn't bad, so I merged =)

**Comment by joaquinelio** [comment]
Oh?
To grasp the **use case**, let's explore a **use case**.
Sounds wrong. Even in long Spanish sentences.

I didnt let it happen in Spanish.  -if he accepts my suggest too-.

**Comment by iliakan** [comment]
Ah, it's good then =)

**Comment by iliakan** [comment]
Thanks.

**Comment by joaquinelio** [comment]
Bytheway, my bot found another bug in yours: 
"148 of 174"
That's terrible, people gets frustrated "the goal is so far".
It counts the example too. 
I could check it to be even, but it would be... wrong.

**Comment by iliakan** [comment]
Is that about pagination? Give me a screenshot please?

**Comment by joaquinelio** [comment]
I'm really sorry.
I should stop wasting everyones time with my stupid jokes.

I meant this, no that interesting,
There are only 173

image

**Comment by iliakan** [comment]
I have a lot of other ongoing stuff, so I probably miss the context sometimes.

So it shows 1 more than there really is?

**Comment by joaquinelio** [comment]
Yes, if you are proud of your 174 articles you shouldn't.  The first one is fake. 

sorry  I did it again. stoooop!
no big deal, silly jokes.

More importan things, "proxy and reflect",
How important is in advanced JS? 
I never read it, but people that started left and they are not the same anymore.

**Comment by iliakan** [comment]
Proxies are used... About once per year at most =)

But it's an interesting stuff to know, may come in handy.

**Comment by iliakan** [comment]
Let me know if the article is bad, I'll update it then.

**Comment by iliakan** [comment]
Please be careful. Maybe it's better for you to abstain though 👩‍🚀

**Comment by joaquinelio** [comment]
I'wont.  But I'll ask... 
Maybe not bad, but too long.  The longest I think. 

haha I just saw the warning, thanks 
the "I wont" refered to "let me know"

**Comment by joaquinelio** [comment]
wait... Proxy is just THE wrappers builder ?

It doesnt look too fancy, I just wonder why class inheritance does not cover every use case   (but I didnt evolve too much from assembler).
PROXY is just the longest article you may consider to split  (I won't decide if it is an issue).

Another long article is indexedDB (I didnt read it). 
But I wouldnt't split it.

**Comment by iliakan** [comment]
Proxy is ... a proxy. It's a wrapper around almost everything including functions. Object inheritance doesn't cover that. It's different.

**Comment by joaquinelio** [comment]
wrappers and class inheritance work is very different, ok, 
but when I try to solve something I look into inheritance first, extend the blueprint instead of the object
Can't do with built-in obj.
Ok, I'll read it.

**Comment by joaquinelio** [comment]
Unrelated to EVERYTHING,

you may want to help other maintaners providing a list
Maintainer needs help to identify abandoned articles, without this we wouldt finish 1st part.
Article / user / date taken / PR
image

**Comment by iliakan** [comment]
Sure, we can. Make it a table? Could you please make a separate issue in https://github.com/javascript-tutorial/es.javascript.info and include others into the discussion for the better progress issue view?

**Comment by joaquinelio** [comment]
I don't need it. I did my own on glitchme (just... good enough) 
The browser capture above is the real result.

I just recommend it for my **colleagues around the world**, maybe they didnt realize they need it.
 
When we took the repo, there were lots of taken and abandoned articles. Tracking them was difficult. Now it's fixed.
Your bot does the rest.  You dont need anything else.

25 articles left.  
With only 3 articles with no @user today,  
the procedure is to clear inactive users with articles taken more than 2 months ago (I post the list with @ mention first) ,
Then a new collaborator just pops.

Reviewers dont pop.   : (

**Pull request merged**
