### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by hrodward**
Grammar fixes

### CODE REVIEW

**Comment by paroche** [comment]
Changes look right to me.

**Comment by iliakan** [comment]
"increase to" seems more correct, no?

**Comment by paroche** [comment]
Are 300ms and 1000ms the end results? If so, yes, "increase to". If it is an amount added to some prior value, then "increase by".

**Comment by iliakan** [comment]
Yes it's increase to. I'll fix that.

**Pull request merged**
