### PR TITLE
change about how some code "waits" for something

### PR DESCRIPTION
**Pull request by KennethKinLum**
I can't think of a better way... somehow the idea of some code "waiting" for something is hard to think about. Is it by some kind of magical `.wait()` or by some kind of `sleep()` call?  I think the mechanism is: it just exists and waits to be called. I can't think of a better way to  put "wait for it" and "wait to be called" together.

### CODE REVIEW

**Comment by iliakan** [comment]
@paroche is there anything to change here, how do you think?

**Comment by jianlin** [comment]
I guess it is like when an object "draws" itself... `obj.draw()`  it is difficult to map the "wait" for something... `obj.wait()`?  It actually is just sitting idle and waiting for some code to invoke it... I guess it can mean ".then()` handlers not being called, waiting for it (the promise settling) -- or waiting for the promise to settle.

**Comment by KennethKinLum** [comment]
I guess it is like when an object "draws" itself... `obj.draw()`  it is difficult to map the "wait" to something... `obj.wait()`?  It actually is just sitting idle and waiting for some code to invoke it... I guess it can mean ".then()` handlers not being called, waiting for it (the promise settling) -- or the 
".then()` handlers not being called, waiting for the promise to settle.

**Comment by paroche** [comment]
I haven't read the article, but original seems OK, probably better, to me. Handlers are always waiting for things.

**Pull request closed without merging**
