### PR TITLE
confusion between arguments and parameters

### PR DESCRIPTION
**Pull request by lumosmind**
when we call a function with some values in braces these values are called as "arguments" instead of "parameters".

### CODE REVIEW

**Comment by iliakan** [comment]
Function parameters are also called arguments.

**Comment by iliakan** [comment]
I'm closing this unless there's more argumentation =)

**Comment by MuhammedZakir** [comment]
Although both of them are used interchangeably, function parameters and arguments are indeed different. [1] I am in favor of making that distinction, but I think it might create more confusion.

[1] https://stackoverflow.com/questions/1788923/parameter-vs-argument

**Comment by lumosmind** [comment]
These terms are generally used wrongly. And if this wrong usage get place in this tutorial it can be shame perspective of engineering.

If we loose difference between **parameters** and **arguments** we can not make technical conversations properly.

[MDN](https://developer.mozilla.org/en-US/docs/Glossary/Parameter)
[microsoft docs](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments)

**Comment by iliakan** [comment]
So:
- we use "parameters" when talking about what's written inside the function declaration,
- we use "arguments" when talking about values, passed to a function.

Correct?

**Comment by lumosmind** [comment]
> So:
> 
> * we use "parameters" when talking about what's written inside the function declaration,
> * we use "arguments" when talking about values, passed to a function.
> 
> Correct?

absolutely right.

**Comment by iliakan** [comment]
Could you please look for parameters/arguments in the text then and update? So that we'll have all fixed appropriately.

**Comment by lumosmind** [comment]
> Could you please look for parameters/arguments in the text then and update? So that we'll have all fixed appropriately.

I found only one conflict in rest of the article and fixed it.

**Review by MuhammedZakir — APPROVED** [review]

**Comment by iliakan** [comment]
Modified SVG manually in the figures.sketch file.

**Comment by iliakan** [comment]
Thanks!

**Pull request closed without merging**
