### PR TITLE
Improve make-army task

### PR DESCRIPTION
**Pull request by MuhammedZakir**
Fix grammar and indent some paragraphs.

Complements javascript-tutorial/en.javascript.info#2081.

### CODE REVIEW

**Comment by iliakan** [comment]
Had to make a few amendments in commit e61bfa26

**Comment by MuhammedZakir** [comment]
> Had to make a few amendments in commit [e61bfa2](https://github.com/javascript-tutorial/en.javascript.info/commit/e61bfa2631d34b32044121767ae6ee13223cb983)

I will keep that in mind. :-)

About that last one, 

```
Now, as you've put so much effort into reading this, and the final recipe is so simple - just use `for`, you may wonder -\- was it worth that?
```

Without backslash, HTML output of this paragraph was strange. That's why, I added it. I forgot what the problem was though.

**Comment by iliakan** [comment]
`--` gets autoconverted to – (long dash) by the rendering engine.

**Comment by MuhammedZakir** [comment]
> `--` gets autoconverted to – (long dash) by the rendering engine.

I see. So does it show correctly now? Also, how long does the site take to show updated content?

**Pull request merged**
