### PR TITLE
Fixed Typographic mistake

### PR DESCRIPTION
**Pull request by arafatjamil01**
#2809

### CODE REVIEW

**Review by joachimklug — APPROVED** [review]
The comma makes it good to read. Also I am wondering why there is a new line introduced?

**Comment by arafatjamil01** [comment]
I am sorry, that newline was introduced by mistake. I have fixed it.

**Comment by iliakan** [comment]
What changed? I see no changes except the newline.

**Comment by arafatjamil01** [comment]
Primarily, a comma was added, a newline was added by mistake. Later the newline was fixed.

This is my first ever public pull request. I have just started contributing to the community.

**Comment by joaquinelio** [comment]
comma fix, ok.

last fix didnt remove newline but a single space before it. d0c69ed

**Comment by iliakan** [comment]
fixed

**Pull request closed without merging**
