### PR TITLE
Exclude negative numbers from the result

### PR DESCRIPTION
**Pull request by 1van0v**

### CODE REVIEW

**Comment by 1van0v** [comment]
From my point of view this task is a bit complicated.
I just sugested a solution that feets the task description.

**Comment by iliakan** [comment]
We can't use features that we didn't teach yet.

**Comment by iliakan** [comment]
Maybe you could suggest another solution instead? 

Thank you!

**Comment by 1van0v** [comment]
As an alternative option I can suggest the following:

`"1.5 0 -5 12. 123.4.".replace(/-\d+(\.\d+)?/, ' ').match(/[1-9]\d*(\.\d+)?/g)`

However, the above solution uses two regular expressions and it does not seem to me that it is an optimal one.

**Comment by iliakan** [comment]
Moved it to another section: please check it out
http://javascript.info/task/find-non-negative-integers

**Pull request closed without merging**
