### PR TITLE
fix head variable redeclaration when pasting to browser dev tools

### PR DESCRIPTION
**Pull request by parabolabam**
When coping js from the task "Searching Algorythm" there is the error thrown
```js
SyntaxError: redeclaration of var head
```

Screenshots attached.
For Firefox:
image

For latest Chrome:

image

### CODE REVIEW

**Comment by iliakan** [comment]
Why did you replace `head` with `face`?

**Comment by iliakan** [comment]
Does that happen only on this site? Or in your scripts? Or in a sandbox?

**Comment by parabolabam** [comment]
All options you provided fits

**Comment by parabolabam** [comment]
@iliakan

**Comment by iliakan** [comment]
Did you run any other examples before this one?

**Comment by iliakan** [comment]
Closed due to inactivity.

**Pull request closed without merging**
