### PR TITLE
minor code formatting for 1-js/02-first-steps/10-ifelse/article.md

### PR DESCRIPTION
**Pull request by bogdanbacosca**
The dots look weird in commit 657e389.
Also the extra ' is not needed from commit 45a2d14.

### CODE REVIEW

**Comment by iliakan** [comment]
What's weird in … compared to ... ?

**Comment by bogdanbacosca** [comment]
@iliakan might look different on my markdown previewer

**Comment by iliakan** [comment]
Please look at the website instead ;)

**Comment by bogdanbacosca** [comment]
@iliakan I double checked the website. It looks just a tiny bit different at the beginning of the Boolean conversion section. I don't think it's a big problem maybe just for consistency's sake. Same goes for the other commit.

**Comment by iliakan** [comment]
Please leave dots as is, they're not a problem at all.

**Comment by bogdanbacosca** [comment]
Done. Reverted that commit.

**Pull request merged**
