### PR TITLE
[discussion] The optional chaining `?.` is an operator

### PR DESCRIPTION
**Pull request by lumosmind**
reference : [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

### CODE REVIEW

**Comment by joaquinelio** [comment]
!!
"not a math operator"? no, no need.
 
The article should mention it has a precedence value too.

**Comment by lumosmind** [comment]
> !!
> interesting.
> The article should mention it has a precedence value too.

actually I realized ?? is an operator when I study on operator precedence table

**Comment by joaquinelio** [comment]
> > !!
> > interesting.
> > The article should mention it has a precedence value too.
> 
> actually I realized ?? is an operator when I study on operator precedence table

yes, that's what convinced me, more than mdn.

**Comment by iliakan** [comment]
?. isn't an operator. Discussed many times.

**Comment by joaquinelio** [comment]
oh...  
#1961 

Then 
1 "despite what MDN stubbornly says many times right now, it is not an operator"

2 we (you) should explain why it has an "operator precedence" value
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table

eppur si muove
the operands are blocks,

**Comment by iliakan** [comment]
@joaquinelio please take a look at the spec as the main source of truth: https://tc39.es/ecma262/

This is the ONLY source of truth. 

MSN just isn't. MDN is a compilation for people who want things simpler. Sometimes MDN authors have their own interpretation, that may be compatible with the spec, and we can even pick it up as well.

About `?.` specifically, here's the discussion with one of the spec authors: https://es.discourse.group/t/optional-chaining-the-syntax-or-the-operator/366/2

Personally, I take words from a spec author as a higher authority than MDN.

Also, we don't call the dot as in "user.name" a "member access operator", like MDN does. There's no such operator in the spec, it's something invented in MDN. So it makes little sense to call `?.` an operator, as it's a "modifed" dot.

**Comment by joaquinelio** [comment]
ok, your kid.
still the best tutorial.

as this doesn't have a "discussion page" like wiki, 
a small note, maybe at the end of the article, would prevent recurring discussions...

**Comment by iliakan** [comment]
Leaving it open for discussions, if there are other opinions.

**Comment by joaquinelio** [comment]
dot as ugly "member access operator" is strong. It IS better for the tutorial to consider it as syntax.
still, why "operator precedence" value

**Comment by iliakan** [comment]
Please, note that the "operator precedence" table is an MDN invention. There's nothing like that in the spec. 

So they give numbers and change them, as they like. 

That's their interpretation of the spec, and I guess it's good for people. Makes it easy to understand why some operator works before another.

We also use this table in the tutorial, when talking about operators. But a dot isn't an operator, at least in JS. Likewise, the `?.` also isn't.

**Comment by joaquinelio** [comment]
ah, that's why I couldn't find it in the spec

NOW we agree.
I guess...  😄

**Pull request closed without merging**
