### PR TITLE
add notes about CSS animation performance

### LINKED ISSUE #2652: Mention performance concerns of CSS animations on properties other than opacity and transform
The CSS `opacity` and `transform` properties are the only 2 best candidates for animation, because they don't trigger repaint. All other properties are less performant. Many articles talk about this fact, for example [this one](https://web.dev/animations-guide/#triggers).

In many examples and tasks in `7-animation/2-css-animations`, properties like `left` or `height` are being animated. They're fine being examples, but I think it'd be great if we could mention that they can usually be replaced by `transform: translate` and `transform: scale`.

### PR DESCRIPTION
**Pull request by ZYinMD**
Closes #2652.

### CODE REVIEW

**Comment by iliakan** [comment]
Thanks! I changed some phrases and rearranged them a little bit, please see https://javascript.info/css-animations#performance

**Comment by ZYinMD** [comment]
Thanks. I want to point out that I have once seen a sentence [here](https://web.dev/animations-overview/#paint) that mentioned that `paint` is often the slowest step, not `layout`.

**Comment by iliakan** [comment]
Better now?

**Comment by joaquinelio** [comment]
Nice job, doc
👍

**Comment by joaquinelio** [comment]
layout vs paint
I guess it depends on cpu/gpu/screen hardware

**Comment by joaquinelio** [comment]
Hi Ilya,
is 440 grammar ok?  sounds odd
I would also write "mozilla gecko" or just "firefox"  so it doesnt sound like a stowaway

**Comment by iliakan** [comment]
@joaquinelio what's wrong? Is 440 a line number?

**Comment by joaquinelio** [comment]
oops sorry
 Not sure 
your Engl is better thn mine

440 The `opacity` property also never causes Layout (also skips Paint in Gecko). We can...

**Comment by joaquinelio** [comment]
my bad "also never" seems correct. 
apologies

but the 2nd silly suggestion may stand...

**Comment by iliakan** [comment]
@joaquinelio Changed to Mozilla Firefox.

**Comment by ZYinMD** [comment]
Yes 440 is a line number. It is now [442](https://github.com/javascript-tutorial/en.javascript.info/blame/4ed51aa48cb667c87e27bfbf05450d1985c80a9d/7-animation/2-css-animations/article.md#L442). 

> The opacity property also never causes Layout (also skips Paint in Gecko). We can...

Yes I agree it sounds weird to say somethings "causes Layout". It'd be better to say it "triggers Layout", even better if we say it "triggers the Layout step".

Line [438](https://github.com/javascript-tutorial/en.javascript.info/blame/4ed51aa48cb667c87e27bfbf05450d1985c80a9d/7-animation/2-css-animations/article.md#L438) also uses "cause" which could be changed to "trigger".

I [originally](https://github.com/ZYinMD/en.javascript.info/blame/b855f6c9db21daa8fee761b79ceb879befb75932/7-animation/2-css-animations/article.md#L424) used `1` and `1` `2` and `1` `2` `3` when talking about these triggers, which was good too.

**Comment by iliakan** [comment]
@ZYinMD changed to trigger.

**Comment by joaquinelio** [comment]
Uhm...
@iliakan 
you added a redundant line 46 (link to bezier is in line 40 too)

sounds to me
 "...you might want to check the *previous article* you *just read* in *this very same chapter*  :)

I would combine it with line 40, or place it before 40 below the heading.

**Comment by iliakan** [comment]
done

**Pull request merged**
