### PR TITLE
README.md translated to Hindi Language

### PR DESCRIPTION
**Pull request by A-DILEEP**
Translation of README.md file in Hindi Language
* Added file README.hi.md
* Can easily get back to English readme content by clicking
<br/>

Screenshot (478)

### CODE REVIEW

**Review by Afirestriker — CHANGES_REQUESTED** [review]
Suggestion base on my understanding. Replace the word अंग्रेजी with हिंदी.

**Comment by A-DILEEP** [comment]
> Suggestion base on my understanding. Replace the word अंग्रेजी with हिंदी.

sure

**Review by Alexandre887 — COMMENTED** [review]
Can you tell me, what's the point of creating a README version in a language other than English in an _English_ tutorial repository? What is the point of people who do not understand English opening this repository at all?

**Comment by A-DILEEP** [comment]
> Can you tell me, what's the point of creating a README version in a language other than English in an _English_ tutorial repository? What is the point of people who do not understand English opening this repository at all?

 Like this README.hi.md priview , if we do same with README.md  and changing the content from 
>This repository hosts the English content of the Modern JavaScript Tutorial, published at https://javascript.info/.(README.md)

To :The respository hosts the hindi content of the Modern JavaScript Tutorial, published at https://javascript-tutorial/hi.javascript.info 
<br/>

Screenshot (478)

 <br/>
I thought it would be helpful to people who does not know English opens this English_tutorial respository at first

**Comment by A-DILEEP** [comment]
> > Can you tell me, what's the point of creating a README version in a language other than English in an _English_ tutorial repository? What is the point of people who do not understand English opening this repository at all?
> 
> Like this README.hi.md priview , if we do same with README.md and changing the content from
> 
> > This repository hosts the English content of the Modern JavaScript Tutorial, published at https://javascript.info/.(README.md)
> 
> To :The respository hosts the hindi content of the Modern JavaScript Tutorial, published at https://javascript-tutorial/hi.javascript.info
> 
> Screenshot (478)
> 
> 
> I thought it would be helpful to people who does not know English opens this English_tutorial respository at first

**Comment by A-DILEEP** [comment]
Or maybe i will try to help in translation the content ,in that specific language respository (https://github.com/javascript-tutorial/hi.javascript.info.git).

**Comment by Alexandre887** [comment]
> Or maybe i will try to help in translation the content ,in that specific language respository (https://github.com/javascript-tutorial/hi.javascript.info.git).

You're absolutely right. Especially in the repository of the Hindi version of the tutorial, this PR will be just right. And please close this PR here.

**Comment by A-DILEEP** [comment]
> 

ok 🙏

**Pull request closed without merging**
