### PR TITLE
Added rest parameter

### PR DESCRIPTION
**Pull request by Slogghykitten5**
I was learning with javascript.info and freecodecamp together and noticed the rest parameter missing in the functions article.
I added it, the paragraph is copied from freecodecamp as it think it is easy to understand.

### CODE REVIEW

**Comment by joaquinelio** [comment]
//javascript.info/rest-parameters-spread

**Comment by Slogghykitten5** [comment]
Shouldn't it be in the basics? or is it because the learner doesn't know about array?

**Comment by iliakan** [comment]
That comes later in the tutorial.

And you're absolutely correct, that's because the learner doesn't know about array yet.

**Comment by joaquinelio** [comment]
Maybe a mention, a vague "other ways" "later in this tutorial"...

**Comment by Slogghykitten5** [comment]
I also think this will be good, so people like me won't get confused. 
Like a link saying "there are [other advanced methods](https://javascript.info/rest-parameters-spread) which we will later in the tutorial"

**Pull request closed without merging**
