### PR TITLE
Change elem.addEventListener(event, handler[, phase]) to elem.addEventListener(event, handler, [phase])

### PR DESCRIPTION
**Pull request by leviding**
RT.

### CODE REVIEW

**Comment by leviding** [comment]
I see that in the tutorial, somewhere optional args write in the form of someMethod(A, B, [C]), and somewhere write in the form of someMethod(A, B[, C]).

Thus, if it doesn't, you can just close this PR.

Thanks 👍

**Comment by lex111** [comment]
@leviding the comma is also optional, look at MDN for an example - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

```
arr.find(callback(element[, index[, array]])[, thisArg])
```

It would be great to unify optional args! :thinking: 
And at the moment I will close this PR, but thanks for your efforts.

**Comment by leviding** [comment]
Got it, thanks!

**Comment by leviding** [comment]
It lines which number are 219 and 238 are written in the form of `, [`, maybe it should be fixed.

**Comment by iliakan** [comment]
Personally, I prefer `param, [optional]` syntax, rather than `param[, optional]`.

The first one looks cleaner.

**Pull request closed without merging**
