### PR TITLE
docs: change `let` to `const`

### PR DESCRIPTION
**Pull request by YangFong**

### CODE REVIEW

**Comment by joaquinelio** [comment]
mmm...
I didnt test it, but you should... :)

**Comment by YangFong** [comment]
There's no secondary assignment, so it's not a problem.

It looks like I've changed all the `let`, but for `for...i`, I found that can not be modified, and adjusted back.

**Comment by joaquinelio** [comment]
wow
my bad
it works
`for (const i = 1; `
fails, but
`for (const i of k ` 
initializees i on every loop.
spec compliant i guess

still, confusing.

**Comment by joaquinelio** [comment]
wow
my bad, it works
`for ( const i , i < nn `
fails, but 
`for ( const i of kk`  
initializes i every loop.
spec compliant I guess

still, confusing

**Comment by YangFong** [comment]
If you delve into the matter, you really don't know why it's enforceable. 

> The following is just my personal understanding of the logic.

I might think that the whole process, each iteration is performed in a different block scope: 

```js
// for..of
{
  {  
    const item = next();
    // ...
  }
  {
    const item = next();
    // ...
  }
}
```

Why is this so? Because `for...of` is not like `for... i`, each update, are in the original basis changes. Instead, it goes directly from one value to the other, without any connection, or correlation, between the two.

**Comment by joaquinelio** [comment]
Ok, 
forloop special treatment.
Nextables dont need the context env an i++ requires

thanks

**Comment by joaquinelio** [comment]
but I dont like it.
🤣

**Comment by joaquinelio** [comment]
But agreed, use const wherever possible

**Comment by YangFong** [comment]
This tweak is not a bug fix, it's a programming style tweak, it's optional, I'm just suggesting a style I like.

**Comment by iliakan** [comment]
We use `let` in most places of the tutorial, for brewity, even though `const` is more suitable.

**Pull request closed without merging**
