### PR TITLE
to make binding more clear

### PR DESCRIPTION
**Pull request by lumosmind**
understanding 

> pre-bound value

  can be little bit hard.

### CODE REVIEW

**Comment by iliakan** [comment]
which is THE reference maybe?

**Comment by lumosmind** [comment]
> which is THE reference maybe?
OLD is more clear. THE can refer both of old and new user value.

**Comment by iliakan** [comment]
"reference to old user object" → maybe more correct → "reference to THE old user object"?

**Comment by lumosmind** [comment]
> "reference to old user object" → maybe more correct → "reference to THE old user object"?

I got it.

**Comment by iliakan** [comment]
Thanks!

**Pull request merged**
