### PR TITLE
Numeric Separators

### PR DESCRIPTION
**Pull request by lumosmind**
there is another way to write numbers more human readable with Numeric Separators.

### CODE REVIEW

**Comment by lumosmind** [comment]
there is [caniuse page](https://caniuse.com/mdn-javascript_grammar_numeric_separators) for numeric separators
It works with decimal numbers , hexadecimals etc. but I didn't want to make article too complicate.

**Comment by iliakan** [comment]
Nice, please see the updated article, is it good enough?

**Comment by lumosmind** [comment]
yes it is very nice but simple typo in there. I open PR for that  #2437

**Comment by iliakan** [comment]
Thanks!

**Pull request closed without merging**
