### PR TITLE
Changed "index" to "position" for splice() method

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
RU - https://github.com/javascript-tutorial/ru.javascript.info/pull/1111

### CODE REVIEW

**Comment by iliakan** [comment]
Why?

**Comment by Ruslan-Aleev** [comment]
I didn't quite understand the question.
1) There are 2 spellings in the text, which is confusing.
See https://github.com/javascript-tutorial/en.javascript.info/pull/2147/files#diff-be29ec7c19bb09855fdabe5c4b5c2a1cL44 and https://github.com/javascript-tutorial/en.jpullascript.info2147/files#diff-be29ec7c19bb09855fdabe5c4b5c2a1cL714
2) Position is not an index position. For example in https://github.com/javascript-tutorial/en.javascript.info/pull/2147/files#diff-be29ec7c19bb09855fdabe5c4b5c2a1cL92 `arr[2] == "JavaScript"`.

**Comment by Ruslan-Aleev** [comment]
By the way, this line also says "index", but you need to write "position" - https://github.com/javascript-tutorial/en.javascript.info/pull/2147/files#diff-be29ec7c19bb09855fdabe5c4b5c2a1cL92

**Comment by Ruslan-Aleev** [comment]
Or I'm confusing something? :)

**Comment by Ruslan-Aleev** [comment]
As I understand it s**P**lice uses position, and slice uses index. This should be indicated in the course text as well.

**Comment by iliakan** [comment]
I suppose index and position are synonyms.

**Comment by Ruslan-Aleev** [comment]
Yes, I already figured it out, thanks.

I was confused by the comment on line 92.
Instead of `// from index 2` worth to specify - `// 2 - index at which to start changing the array`.
In russian it is also not entirely clear:
`// с позиции 2`, but it is correct to write `// на позиции 2` or `// вместо позиции 2`.

Although, perhaps this only confuses me :) Anyway, thanks for the awesome site!

**Pull request closed without merging**
