### PR TITLE
Fixed image display issue + smart header issue

### PR DESCRIPTION
**Pull request by engag1ng**
- [x] iframe was not displaying so I added screenshots instead.
- [x] Smart header had four backticks instead of three backticks

### CODE REVIEW

**Comment by smith558** [comment]
@engag1ng Hi! The iframes are loading just fine for me. Could you provide more details/screenshots of what's not working for you?

**Comment by engag1ng** [comment]
image
This is another thing with the HTML code not loading from src.

image
This is how every iframe looks for me.

I already tried to open the repo with another browser (Chrome) because I thought that Brave was maybe blocking iframes but no success. Seems like nothing with a src tag loads.

**Comment by joaquinelio** [comment]
**About smart header 4 backticks**

Did you test it?
There are 4 for a reason, they are nested blocks. There's a big smart box that includes smaller 3 tick code block.
Nested blocks dont work in github, that's why you need to test in a local server

**Comment by smith558** [comment]
> **About smart header 4 backticks**
> 
> Did you test it? There are 4 for a reason, they are nested blocks. There's a big smart box that includes smaller 3 tick code blocks. Nested blocks dont work in github, that's why you need to test it in a local server

Good catch!

**Comment by engag1ng** [comment]
My bad. Didn't realise that you shouldn't view this on GitHub but rather on the website. Closing now. But thanks for the quick support :)

**Comment by smith558** [comment]
@engag1ng Thanks for your effort anyway! 🙂

**Comment by joaquinelio** [comment]
https://github.com/javascript-tutorial/server

Good luck!

As a Spanish turorial maintainer,
I Did my part, there and here, w successful and rejected contribs.

**Pull request closed without merging**
