### PR TITLE
Mention scrollX and scrollY

### PR DESCRIPTION
**Pull request by paroche**
They are how pageXOffset and pageYOffset are listed in MDN. For completeness, and so a search for one of those terms will bring up this page.

### CODE REVIEW

**Comment by iliakan** [comment]
Can we safely say that `scrollY` is an alias of `pageYOffset`? (IE9 doesn't exist for us, IE11 is the most recent version we may take into account).

**Comment by paroche** [comment]
I based my phrasing on the MDN Web Docs:
[https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY](url)
[https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset](url)

I figured that the term "alias" was probably being used there in a formal way, so that `pageYOffset` was technically an alias for `scrollY`, not the other way around. But I don't know for sure.

`caniuseit.com` also describes `pageYOffset` as "non-standard":
[https://caniuse.com/?search=scrolly](url)

(even though it's apparently the only syntax recognized by IE11 (and IE9-IE10)), and, based on a cursory examination of the site, seems to be recognized everywhere `scrollY` is recognized).

**Comment by iliakan** [comment]
The spec https://drafts.csswg.org/cssom-view/#dom-window-scrolly mentions both.

It also says "The pageYOffset attribute must return the value returned by the scrollY attribute."

Both attributes are read-only.

It makes them literally aliases, or do I miss something?

**Comment by paroche** [comment]
It seems to be listing `scrollY` as primary -- it's defined as having to return a certain value, whereas `pageYOffset` is defined in terms of `scrollY`: 

"_The scrollY attribute must return the y-coordinate, relative to the initial containing block origin, of the top of the viewport, or zero if there is no viewport._

_The pageYOffset attribute must return the value returned by the scrollY attribute._"

So it looks to me like `scrollY` is the "real" name and `pageYOffset` is the "alias". 

(Typically, an "alias" is not a real name: [https://www.merriam-webster.com/dictionary/alias](url))

If that still doesn't sit well, I think the main thing is just to mention `scrollY` and `scrollX` so people looking for those functions will be able to find them (and `pageYOffset` et al).

**Comment by iliakan** [comment]
Your suggestion is great, just exploring options how to put it better.

**Comment by iliakan** [comment]
Added, thanks!

**Comment by paroche** [comment]
Looks good.

**Pull request closed without merging**
