### PR TITLE
Edit sentance syntax in closure article

### PR DESCRIPTION
**Pull request by michael-mcgee**
While reading through the closure article I noticed a sentence where the syntax seemed a little off.

This pull request fixes the small syntax error and hopefully improves the readability.

### CODE REVIEW

**Comment by paroche** [comment]
Yes, change is good.

**Comment by iliakan** [comment]
@paroche you say that the change is good, but close (not merge) the PR.

Is it a mistake?

**Comment by paroche** [comment]
Yes, meant to just approve. Not sure if you all wanted me to merge or just comment. But did not mean to close it.

**Comment by iliakan** [comment]
If you close a PR, you deny it.

**Comment by paroche** [comment]
Yeah, that's kind of becoming clear.

**Pull request merged**
