### PR TITLE
class syntax vs object literal

### PR DESCRIPTION
**Pull request by lumosmind**
> To tell the truth, the notations are not fully identical. There are subtle differences related to object inheritance (to be covered later), but for now they do not matter. In almost all cases the shorter syntax is preferred.

I think this paragraph talks about prototypal inheritance but when we work with object literal there is no difference between  `sayHi: function() {` and `sayHi() {`  booth syntaxes add property as own property of object itself, does not add property to object's `prototype` like es6 class syntax.

### CODE REVIEW

**Comment by iliakan** [comment]
What is `user.__proto__` is changed? Then, `super` keyword inside these two notations behaves differently.

**Comment by lumosmind** [comment]
I couldn't understand. Doesn't `super` keyword belong to es6 class syntax? But These paragraph is about object literal. What do I miss?
Please throw some example snippets. I am very confused.

**Comment by iliakan** [comment]
Sure, here you are.

This works (shows 1)
```js
let user = {
  f() { 
    super.f();
  }
};

Object.setPrototypeOf(user, {
  f() { alert(1) }
});

user.f();
```

This doesn't (shows error):
```js
let user = {
  f: function() { 
    super.f();
  }
};

Object.setPrototypeOf(user, {
  f() { alert(1) }
});

user.f();
```

**Comment by iliakan** [comment]
Closing it meanwhile, let me know if should be open.

**Comment by lumosmind** [comment]
thanks for examples I will mediate on them.

**Pull request closed without merging**
