### PR TITLE
declarations vs calls

### PR DESCRIPTION
**Pull request by lumosmind**
I think article talks about "closures". If we talk about closures, calling a function in another function does not create links if arguments are not objects.
So if the subject is "closures", it should be "declarations" instead of "calls".

### CODE REVIEW

**Comment by iliakan** [comment]
Actually, "calls" is correct here. Variables that are "outside" are kept due to closures mechanics, not because they are roots.

**Comment by lumosmind** [comment]
Can you give an example? I couldn't understand what you mean.
Can nested called function reach outer lexical environment?

**Comment by iliakan** [comment]
Just a nested call, like here:

```js
f();

function f() {
  g()
}

function g() {
   // <-- here the calls chain is f → g
}
```

**Comment by lumosmind** [comment]
ahh I got it now g() can reach local variables of f(). Thank you

**Comment by iliakan** [comment]
No, it can't (how could it?) ;)

They are "roots" meaning that they are retained in memory (not thrown away). So that after `g()` is done, the execution of `f()` can continue.

**Pull request closed without merging**
