### PR TITLE
more descriptive boundary value for Math.round

### PR DESCRIPTION
**Pull request by lumosmind**
3.5 is a boundary value for Math.round() so use 3.5 as example can be more descriptive.

### CODE REVIEW

**Comment by iliakan** [comment]
Sorry, but quite the opposite: 3.5 is the edge case, while 3.6 is more obvious.

**Comment by iliakan** [comment]
We describe the main scenario here, not edge cases.

**Comment by lumosmind** [comment]
but 3.5 shows that how does round() work. 3.6 does not give a clue about that.

**Comment by iliakan** [comment]
Well, 3.2 shows rounding down, while 3.6 shows rounding up.

If you consider `3.5` an important edge case, we can add it.

**Comment by lumosmind** [comment]
> Well, 3.2 shows rounding down, while 3.6 shows rounding up.
> 
> If you consider `3.5` an important edge case, we can add it.

yes it could be very efficient

**Comment by iliakan** [comment]
Done:
```
Rounds to the nearest integer: `3.1` becomes `3`, `3.6` becomes `4`, the middle case: `3.5` rounds up to `4` too.
```

**Comment by lumosmind** [comment]
thank you

**Pull request closed without merging**
