### PR TITLE
Update task.md

### PR DESCRIPTION
**Pull request by maurodibert**
I'm pretty sure that if this work, it's hardcoded! (LoL) It's that the solution button must be in the next line...

### CODE REVIEW

**Comment by iliakan** [comment]
Wait, what did you change? Added spaces?

**Comment by maurodibert** [comment]
Yeap!

And have this question: I'm doing the translation of this article (https://javascript.info/variables), and github doesn't render the `smart header`. There's a special way of doing it?

**Comment by iliakan** [comment]
Spaces change something? They shouldn't.

Github doesn't render some site-specific things, that's ok.

**Comment by maurodibert** [comment]
Reading on Markdown docs, two spaces is equivalent to add a new blank line but I thought probably didn't work and if did, hardcoded.

Sorry about that and thanks for the explanation!

**Comment by iliakan** [comment]
Is something wrong there? Please tell me.

**Comment by iliakan** [comment]
What's the purpose of the fix?

**Comment by maurodibert** [comment]
Yeap, at least for me visually and the consistency with the other articles:: see that "Run the demo" it's "glue" with "solution", instead of two lines, one line each button.

**Comment by iliakan** [comment]
Oh, is it ok now?

**Pull request closed without merging**
