### PR TITLE
use property value shorthand to add as method

### PR DESCRIPTION
**Pull request by lumosmind**
We can also use **property value shorthand** concept for creating method.

### CODE REVIEW

**Comment by iliakan** [comment]
Are you sure that such example is needed in that exactly place?

**Comment by lumosmind** [comment]
The example uses  property value shorthand concept  which is discussed previous article and shows another way to declare a method. It is good for reinforcing learned concepts. And it shows we can manage functions like normal variables.

**Comment by iliakan** [comment]
Yes, but here we concentrate on another topic. I try not to dilute the user attention.

**Comment by lumosmind** [comment]
yes it makes sense. Subjective situation.

**Pull request closed without merging**
