### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by maurodibert**
Hi Ilya! I'm not sure if there is any other intention using a function User() instead of the class, but since you were comparing, maybe could be an error.

### CODE REVIEW

**Comment by iliakan** [comment]
Why did you close this?

**Comment by maurodibert** [comment]
Hi! Because I was wrong ;-)

**Comment by iliakan** [comment]
As we're talking about classes here, I'd agree to use `class` instead.

**Comment by iliakan** [comment]
Seems better, no?

**Comment by maurodibert** [comment]
I thought that the first time but then didn't know if you wanted to use functions for any other internal specification. i'll restore the branch and commit! ;-)

**Comment by iliakan** [comment]
I changed one more word there and committed locally, thanks!

**Comment by maurodibert** [comment]
Cool! Thanks to you one more time!

**Comment by maurodibert** [comment]
And when I have a little bit of time, I will start doing these things locally and pushing those exercises (and others) that I couldn't here! Have a nice day Ilya!

**Comment by iliakan** [comment]
By the way, I requested changes for #1053

Did you see that?

**Comment by maurodibert** [comment]
hehe yeap! I was answering you that in the previous comment! But I kept the branch not to forget!

**Pull request closed without merging**
