### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by hrodward**
Grammar suggestions

### CODE REVIEW

**Comment by iliakan** [comment]
Why not "**The** `__proto__` is not a property of an object, but an accessor property of `Object.prototype`:..." ?

**Comment by hrodward** [comment]
In my opinion, using "The" would require to specify what __proto__ is, as in "The __proto__ accessor..."

**Comment by paroche** [comment]
Should not be a "The" before "`__proto__`", because "`__proto__`" in this context already indicates a specific thing, so would not have to be specified further with "the"; it is already the only member of its class of things (of things that are "`__proto__`"). 

It's like if you have a dog Rover, you don't say "The Rover is a sheep dog", just "Rover is a sheep dog."* (never met a dog named "Rover", BTW, but it's a classic example dog name). 

**But**, if you had written "`__proto__` **property** is not a property of an object...", THAT would require a "The" before "`__proto__`" (i.e., should have "The `__prototype__` property is not ...") because then it is one of several (more than one) possible properties.
<br>
\* (Actually, you **might** refer to the aforementioned hypothetical dog as "The Rover" if you thought he was putting on airs or something, such that his name had become a title, like "king", but that's another story.)

**Comment by iliakan** [comment]
Thanks a lot for the explanations!

**Comment by paroche** [comment]
Hope was somewhat clear.

**Comment by paroche** [comment]
Please see changes above.

**Pull request merged**
