### PR TITLE
Testcases/function object 5

### PR DESCRIPTION
**Pull request by Logan-Schelly**

### CODE REVIEW

**Comment by iliakan** [comment]
Can you make tests simpler please? Maybe split into functions instead of `makeTestCaseName` ?

**Comment by Logan-Schelly** [comment]
Sure!  I'll try to get that done this evening.

**Comment by Logan-Schelly** [comment]
I've committed the changes to the branch and pushed it to my github account's version of the branch.  Let me know if there's anything else I need to do.  I'm done most of my school work on a single branch, so I'm still getting used to this whole pull request thing.

**Comment by iliakan** [comment]
Looks good!

**Pull request merged**
