### PR TITLE
Fix language errors and improve style

### PR DESCRIPTION
**Pull request by peterhauke**
Technologies don't really "play" together, but they can "work" together.
It is best to avoid words such as "crippled", when "restricted" or "limited" are perfectly acceptable.
Change HTTP to HTTPS in the URLs in the paragraph above the image as HTTPS is in the image. I thought of changing anysite.com to javascript.info in this paragraph to match the image, but I decided not to. I may raise this later as a PR for you to decide.

### CODE REVIEW

**Comment by peterhauke** [comment]
Thanks, @joaquinelio 

Searching for "avoid ableist language" in google brings up many reasons why using "crippled" is not recommended in English.

Apart from that, I am not sure that the word "crippled" would properly describe the situation here. Nothing is malfunctioning or is being damaged. So, we could make a case that "crippled" is wrong in this particular case anyway, from a purely technical point of view.

Are you saying that it is easier to translate read/update/delete into another language? That's interesting.

**Comment by joaquinelio** [comment]
> Searching for "avoid ableist language" in google brings up many reasons why using "crippled" is not recommended in English.
> 
> Apart from that, I am not sure that the word "crippled" would properly describe the situation here. Nothing is malfunctioning or is being damaged. So, we could make a case that "crippled" is wrong in this particular case anyway, from a purely technical point of view.
> 

Just read, thanks!
Two strong arguments, for any language.

> Are you saying that it is easier to translate read/update/delete into another language when / is used? That's interesting.

It IS hard to read as a normal reader.
I still fix it when it doesn't fit, Spanish doesn't allow me to translate it that way.
But when it is related to explaining code or structs, sometimes it makes it easier for me programmer to catch. 
so I treat it as a special markdown to feel less guilty.
Just like to avoid writing "The force equals the mass times the acceleration", I'll never understand that way.

**Comment by iliakan** [comment]
And what's the wrong with the "Let's see" introductory phrase?

**Comment by peterhauke** [comment]
English is very forgiving and most people will understand what "technologies play well" means in this context, that's why I wrote 'Technologies don't really "play" together'.

"what's so special about JavaScript" is a very nice phrase which at the same time questions the importance of JavaScript and suggests that some people don't think it is important, at least that's the way that I understand it. "Let's see" at the beginning just weakens the strength of that message, but it is not wrong. Swapping "we can" in the second phrase becomes necessary if "Let's see" is removed.

I suggest that we just close this PR. When I have some time, I will read it again and correct just the language errors and not try to improve the style.

**Comment by iliakan** [comment]
Dear @peterhauke,

As a person whose English is non-native, I surely lack the understanding of intricate style aspects and undertones of the language.

Although, I'm trying to learn the reason of changes before blindly accepting them.

Thank you very much for your improvements! ❤️

**Pull request closed without merging**
