### PR TITLE
Create task2-solution.md

### PR DESCRIPTION
**Pull request by juuni26**
Adding more problem related arrow function to deepen understanding.

### CODE REVIEW

**Comment by iliakan** [comment]
This supposed to be one more task, right?
You should structure it the same way as an existing one: a task resides in a folder.

**Comment by juuni26** [comment]
thanks for the feedback. let me know if there is more that i can help 😄

**Comment by iliakan** [comment]
Is that supposed to be a one more standalone task?

**Comment by juuni26** [comment]
sorry my bad. didn't realize it until before

**Comment by iliakan** [comment]
I'm sorry, that doesn't look good.

I don't see why a variable is needed. Maybe you could make the task simpler.

**Comment by iliakan** [comment]
Closing this due to many mistakes in English language and in file names.

**Pull request closed without merging**
