### PR TITLE
Improve awkward sentence structure

### PR DESCRIPTION
**Pull request by smith558**
The original sentence was a bit awkward to understand and also not grammatically correct.

### CODE REVIEW

**Comment by joaquinelio** [comment]
👍 
Maybe the ugliest.

There are many pending grammar PR.
I don't agree with them all,  but I dont do the review because I m not a native English speaker.

**Comment by joaquinelio** [comment]
Why 
43 Let's  Let’s
Careful, ’ is a formating char

**Comment by smith558** [comment]
> Why 43 Let's Let’s Careful, ’ is a formating char

Yes, I just noticed that. For some reason, my autocorrect fixed that for me and I accidentally pushed it.

**Comment by smith558** [comment]
> Why 43 Let's Let’s Careful, ’ is a formating char

Fixed.

**Pull request merged**
