### PR TITLE
minor

### PR DESCRIPTION
**Pull request by qucumbah**

### CODE REVIEW

**Comment by iliakan** [comment]
Error? Why?

**Comment by qucumbah** [comment]
if you execute the code it throws:
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
the description even says "Here’s an example of such code (it doesn’t work – why? fix it?)"

**Comment by iliakan** [comment]
Right, thanks!

**Comment by iliakan** [comment]
There was an error there indeed.

**Pull request closed without merging**
