### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by ellie-heidari**
Small change in the sentence.

### CODE REVIEW

**Comment by joaquinelio** [comment]
( I'm not a native English speaker)

Interesting.
I think both are correct, but it's not about grammar. They are not strictctly logically the same.

Maybe the change is easier to read, still correct?

**Review by Afirestriker — APPROVED** [review]
Grammar Checked. LGTM

**Review by komalagra — COMMENTED** [review]
LGTM.

**Review by FloffyGarlic — APPROVED** [review]
I like this change. The correction definitely feels more natural

**Review by smith558 — APPROVED** [review]

**Comment by smith558** [comment]
Thank you for your contribution! 🙂

**Pull request merged**
