### PR TITLE
Improve some English grammar problems

### PR DESCRIPTION
**Pull request by tunggnu**
I did it with the help of the Grammarly tool.

### CODE REVIEW

**Comment by iliakan** [comment]
"For example" doesn't require a comma.

Maybe @paroche could say better here.

**Comment by paroche** [comment]
I agree that it's better without the comma. However, it may be a bit better with a semicolon _before_ "for example", a change I am about to make.

**Comment by paroche** [comment]
Don't want this overriding what I just did. I think the semicolon is only somewhat better. I considered an m-dash, but went w/ the semi. Preceding comma wasn't bad, though. Following comma would be less good.

**Comment by iliakan** [comment]
Thank you!

**Pull request closed without merging**
