### PR TITLE
add an asyncronous test for throttle

### PR DESCRIPTION
**Pull request by dagolinuxoid**
The addition to the main test.js guarantees that only unique calls are made.

### CODE REVIEW

**Comment by dagolinuxoid** [comment]
It closes #716. However in order to make it work properly *index.html* file on Plunker **should** be edited as well:
Its current state is :
```html
<!doctype html>
<script src="https://en.js.cx/test/libs.js"></script>
<script src="test.js"></script>
<script>

  // ...Your code...

</script>

</html>
```
Its required state should be the fallowing:
```html
<!doctype html>
<script src="https://en.js.cx/test/libs.js"></script>
<script>

  // ...Your code...

</script>
<script src="test.js"></script>
</html>
```

**Comment by iliakan** [comment]
@dagolinuxoid why should we edit index.html?

For other tests it's fine, what's so special about the new test?

**Comment by dagolinuxoid** [comment]
Otherwise it's not going to work, that's most likely due to I used the `done` parameter  for *it* spec. I understand that even small altering of index.html can be a troublesome so it's up to you to make a decision.

**Comment by dagolinuxoid** [comment]
I'll try to solve it without altering html file. If it's not trivial I'll comment here and you can decide either accept or decline the PR. So hold on till evening.

**Comment by iliakan** [comment]
Thank you!

**Comment by dagolinuxoid** [comment]
You put all the code inside of anonymous function and now all things are working properly. Good job.

**Pull request closed without merging**
