### PR TITLE
Removing unnecessary and confusing language

### PR DESCRIPTION
**Pull request by MondoBurrito**
The line: " not a "magical language structure", " is confusing and unnecessary. It is important to point out that functions are values, but these extra words only serve to muddy the point the author is trying to make.  We need to make this material as clear and concise as possible.

### CODE REVIEW

**Comment by Rnbsov** [comment]
Personally, I don't think there is anything superfluous in this

**Comment by leviding** [comment]
I think it doesn't matter.

**Comment by MondoBurrito** [comment]
> I think it doesn't matter.

Probably because you are already really good at coding ;)  From my perspective,  as someone who is literally learning the very first steps of JS and struggling to make sense of it all, any extra, confusing and unnecessary words should not be in the tutorials.

**Comment by joaquinelio** [comment]
"magic" is metaphoric, It means there is nothing overcomplicated.
You may have a different style of writing (eg "just another value"), but the point is not superfluous.

**Comment by smith558** [comment]
Well, in some languages functions are kind of magical structures. To me, it well conveyed the point that they are equal to objects, as everything else in JS.

**Pull request closed without merging**
