### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by paroche**
Change wording on inherited methods state changes. Not perfect but probably better.

### CODE REVIEW

**Comment by iliakan** [comment]
Isn't the new sentence a bit long and complicated? 😊

**Comment by paroche** [comment]
Well, I said it wasn't perfect. I'll look at it again, though.

**Comment by iliakan** [comment]
maybe remove "we need to be clear" ?

**Comment by paroche** [comment]
Yeah. I was looking for a bridging phrase, but that's a bit awkward. I'm working on it....

**Comment by iliakan** [comment]
The important thing is that methods reside in the parent object, but modify the state of the child object, not the parent one.

**Pull request closed without merging**
