### PR TITLE
"bigint" is also numeric type

### PR DESCRIPTION
**Pull request by lumosmind**
To keep question simple and precise we could change "numeric" with "number typed". Because term numeric involves both "number" type and "bigint" type. But the solution and test cases want us to solve this question for "number" type.

### CODE REVIEW

**Comment by iliakan** [comment]
There's a type "number". And we'd better not confuse people using the same word for bigints, as they are "bigint".

Both are numerical types. Similar to many other languages, where there are "float" for decimals, "int" for integers, both are numeric types.

**Comment by lumosmind** [comment]
I think I couldn't express my ideas. Because we are talking about same things.  If we use "numeric" instead of "number typed", we need to expand solution to cover bigint type. we need to emphasize number type or change the solution.

**Comment by iliakan** [comment]
Oh, I see now, sorry.

You are correct. Although, "number typed" feels a bit awkward..

**Comment by lumosmind** [comment]
> Although, "number typed" feels a bit awkward..

I just try to create solution but English is not my main language :)

**Pull request closed without merging**
