### PR TITLE
Add note for non-strict mode and change wording

### PR DESCRIPTION
**Pull request by romanstetsyk**
Checked grammar with Grammarly

### CODE REVIEW

**Comment by romanstetsyk** [comment]
I'm not a native speaker; my level of English is C1 (advanced)

**Comment by iliakan** [comment]
Thanks for removing "the", and hesitating about the other fix.

**Comment by romanstetsyk** [comment]
You used "in strict mode" and "in non-strict mode" without "the" throughout all other articles. I tried to make it uniform

**Comment by iliakan** [comment]
There should be no "the", thanks for that. =)

**Pull request closed without merging**
