### PR TITLE
BigInt Type added in primitive types

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
The new Bigint type was not added to the primitive types I added it to the primitive type please tell me where ever it needs to be added. So that the whole documentation is consistent everywhere.

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
BigInt is currently in stage 4 of approving and is just left to be shipped to Safari rest its applicable everywhere I think we should add it.

**Comment by iliakan** [comment]
It's not in https://tc39.es/ecma262/ yet though

**Comment by ajitsinghkaler** [comment]
It's there in it.

**Comment by iliakan** [comment]
I shouldn't have accepted this PR. It's terrible. It ignores all the flow of the tutorial and just sticks BigInt where they shouldn't be.

**Comment by iliakan** [comment]
and uses `typeof` operator even before it's explained.

**Comment by ajitsinghkaler** [comment]
Please tell me how can I improve I didn't know in which firm you want this.

**Comment by iliakan** [comment]
I will rewrite that. Just please look at the tutorial in future PRs, so that you don't use unexplained operators in your code. Our purpose is to explain things well, not just list them as the manual does.

**Comment by ajitsinghkaler** [comment]
I've just started contribution to open source please forgive me this time I'll learn from the way you articulate your PR and terms I'm really sorry for this time. Thank you for for correcting my PR

**Comment by iliakan** [comment]
thank you for your efforts, surely you can do better

**Pull request merged**
