### PR TITLE
assign instead of copy

### PR DESCRIPTION
**Pull request by lumosmind**
Methods are passed by **reference** not copied like primitives.

### CODE REVIEW

**Comment by iliakan** [comment]
Copied by reference. That's fine.

**Comment by lumosmind** [comment]
> Copied by reference. That's fine.

Analogy is the murder of truth :)

**Comment by iliakan** [comment]
I don't understand. “copy by reference” is a well-known term.

**Comment by lumosmind** [comment]
> I don't understand. “copy by reference” is a well-known term.

you are right. that is actually what  I mean: "copying an object" is different from "copying by reference".
this tutorial consists very deep level knowledge about js. So, using right term in convention, is very important to figured out complex things.

**Pull request closed without merging**
