### PR TITLE
👾 just add missed space and as it turned out, not only

### PR DESCRIPTION
**Pull request by Rnbsov**
image

### CODE REVIEW

**Comment by joaquinelio** [comment]
exmple seems clear...
You may want to add spaces after comma too. line below.

**Comment by Rnbsov** [comment]
> exmple seems clear... You may want to add spaces after comma too. line below.

not sure it neccesery

**Comment by joaquinelio** [comment]
the comments show the actual output
"alert" doesnt show brackets, quotes nor spaces

**Comment by Rnbsov** [comment]
what about the Numbers article?  There, when using the toFixed() method, there are quotes that emphasize that the method returns exactly the string 

image

**Comment by joaquinelio** [comment]
Right!
Then I agree with the quotes now, but no with the brackets, the result is string.

**Comment by iliakan** [comment]
Usually there are no quotes when we put output after //.

The `toFixed` is an exception, because it's important that there's a string there.

We can replace alerts by console.logs, but it's another story...

**Pull request closed without merging**
