### PR TITLE
it also work as Map value

### PR DESCRIPTION
**Pull request by lumosmind**
```
let john = { name: "John" };

let map = new Map();
//map.set(john, "...");
map.set("x",john);

john = null;
map.keys().next().value
```

### CODE REVIEW

**Comment by joaquinelio** [comment]
not sure...   
Right, the sentence may be more accurate I guess

But 
it is not exactly wrong without
it should be obvious at that moment (same as array item I guess)
and 
it is trying to do a point about "key", 
the object as a value is not going to change anything, it feels... a stowaway

**Comment by lumosmind** [comment]
> not sure...
> Right, the sentence may be more accurate I guess
> 
> But
> it is not exactly wrong without
> it should be obvious at that moment (same as array item I guess)
> and
> it is trying to do a point about "key",
> the object as a value is not going to change anything, it feels... a stowaway

this commit aim at completeness. the subject is garbage collector behavior so  object as a value is absolutely going to change something.

**Comment by joaquinelio** [comment]
Got it, garbage collection is the important point here
the author put it only as the introduction to weakmap 

If you add "or value"  you should add the consequence:  the item stays. 
As expected, so I wouldn't add it.  (the item & the object stay, map or weakmap)  

and following 
"  `WeakMap` is fundamentally different in this aspect."  seems odd now
you'll need to add you are referring to key only

**Comment by iliakan** [comment]
The main point here is about keys. Values can be anything.

**Pull request closed without merging**
