### PR TITLE
Case and filesystems

### PR DESCRIPTION
**Pull request by joaquinelio**
* not comfortable in adding this so early in the tutorial but there is no "filesystem" topic.
You may want to drop it if it is too off-topic or distracting, or put it somewhere else.

* This is not THE reason for using all-lowercase. May have a pretty offtopic one.

### CODE REVIEW

**Comment by kkanekii** [comment]
Another section for this would be nice

**Comment by joaquinelio** [comment]
problem is,
there is no filesystem for js

node has its own libs to work with paths

**Comment by kkanekii** [comment]
Hmm, then theres no need for a seperate section, a small addition should do, I can help out if required

**Comment by joaquinelio** [comment]
any idea welcomed, 

I dont like this PR.  It s not a real js issue

but beginners working on windows may find 
their local code not working when they move it to the server or other clients.

"CamelCase not good for filenames"

**Comment by iliakan** [comment]
That's an issue. But not quite a JS thing.

Linux guys usually understand this well, so they have no problem.

Mac/windows have this issue when going to Linux - that's true, but again not JS.

**Pull request closed without merging**
