### PR TITLE
rephrase

### PR DESCRIPTION
**Pull request by joaquinelio**

### CODE REVIEW

**Comment by joaquinelio** [comment]
ha ha !
cant explain why

I wanted "closes the conn that became old" 
it IS old, but I erased that too

I think it reads better, 
and it is still evident,  event -> closes the connection, 
the reader goes to code, it reads "closed  because obsolete, I think it's ok

**Comment by joaquinelio** [comment]
oops you just did it again

it s ok

**Comment by iliakan** [comment]
updated

**Comment by iliakan** [comment]
hopefully better now

**Pull request closed without merging**
