### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by Violet-Bora-Lee**

### CODE REVIEW

**Comment by Violet-Bora-Lee** [comment]
When the multiple tasks run "right after" another, it is synchronous tasks.

**Comment by iliakan** [comment]
If we schedule something to run after something, that's async.

**Comment by iliakan** [comment]
The key word is not "right now", but 'right after the code is complete'. 

Still, if the phrase confuses you, maybe we should remove it?

**Comment by Violet-Bora-Lee** [comment]
Thanks for your comment. Yeah, there could be ppl like me I guess.

**Comment by iliakan** [comment]
removed this phrase

**Pull request closed without merging**
