### PR TITLE
Update article.md (Template Element Page)

### PR DESCRIPTION
**Pull request by irshadbaiwa**
Grammar correction

### CODE REVIEW

**Comment by joaquinelio** [comment]
its

**Comment by irshadbaiwa** [comment]
> its

The apostrophe('s) here indicates possession 
[Wikipedia](https://en.m.wikipedia.org/wiki/Apostrophe)

**Comment by joaquinelio** [comment]
like
The boss ignores his efforts.

* but I'm not a native speaker.

**Comment by iliakan** [comment]
fixed.

**Pull request closed without merging**
