### PR TITLE
redundant

### PR DESCRIPTION
**Pull request by joaquinelio**

### CODE REVIEW

**Comment by joaquinelio** [comment]
or maybe leaving it and erasing the 2nd sentence.

**Comment by joaquinelio** [comment]
last change, just an idea.  i think it's a strong image 
didnt test it

I see lines 112 114 a little ambiguous

**Comment by iliakan** [comment]
Sorry, but "avatar traveling in games" isn't a familiar concept for many people, please remove it.

**Comment by iliakan** [comment]
Thanks!

**Pull request merged**
