### PR TITLE
fix grammar mistakes 

### PR DESCRIPTION
**Pull request by Rnbsov**
Corrected the same grammatical errors as in this pr

https://github.com/javascript-tutorial/en.javascript.info/pull/2919

### CODE REVIEW

**Comment by Rnbsov** [comment]
image

**Comment by iliakan** [comment]
Are you sure, the "won't" fix is needed? Is this a mistake, to say like I did?

**Comment by iliakan** [comment]
fixed "on the left/right", not sure about "won't".

**Comment by joaquinelio** [comment]
i prefer "will not be".
not about grammar.
cleaner and stronger.

**Pull request closed without merging**
