### PR TITLE
Confucius never said black cat quote

### PR DESCRIPTION
**Pull request by leeyc0**
Confucius never said anything about black cat

Ref: https://www.washingtonpost.com/world/2019/03/25/chinese-proverb-that-russia-cited-respond-mueller-report-does-not-appear-be-chinese-proverb/

### CODE REVIEW

**Comment by iliakan** [comment]
Who said it then? Maybe we can replace it with another, real Chinese metaphor?

**Comment by leeyc0** [comment]
Apparently this "quote" actually came from a Soviet drama. The character who said this "quote" claimed it came from Confucius, and the misunderstanding stuck since then.

**Comment by iliakan** [comment]
What should be a proper replacement? :ponder:

**Comment by leeyc0** [comment]
Unfortunately I am still looking for a proper replacement...

**Comment by leeyc0** [comment]
I think the best one would still be Tao Te Ching, given on the context.
https://www.wussu.com/laotzu/laotzu01.html

名可名，非常名
The name that can be named is not the eternal name.

**Comment by iliakan** [comment]
Sounds good! 🚀  🎸

**Pull request merged**
