### PR TITLE
Either quotation marks or italicization

### PR DESCRIPTION
**Pull request by u-n-known**
Highlighting twice is unnecessary.

### CODE REVIEW

**Comment by iliakan** [comment]
You mean italic is bad there?

**Comment by u-n-known** [comment]
@iliakan, the actual problem is that you can't figure out wether it's a cite or the apostrophes suggest some kind irony because you can not really make a web page alive, shortly because it's a personification. 

In the first case the apostrophes suffice, for the second I wouldn't even mark it up as it is kind of difficult to mark something up like irony, and if so it would've been sufficient to italicize just "alive" as I suppose you know so I don't think this was your intend. Or am I mistaken?

**Comment by iliakan** [comment]
@paroche could you please advise here?

**Comment by paroche** [comment]
Never caught my attention before (the one or two times I read it), but, now that it's come up, I think it would be a bit better with just the quotes (not apostrophes), without the italicizing.

**Comment by u-n-known** [comment]
>  quotes (not apostrophes)

Oh, you're right.

**Comment by iliakan** [comment]
Thanks!

**Comment by paroche** [comment]
@u-n-known  
<i>quotes (not apostrophes)

Oh, you're right.</i>

Well, you got it in the title! :-)

And, of course, in JS itself they are almost interchangeable.

**Pull request merged**
