### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by paroche**
Replace 'cause' with 'case'.

### CODE REVIEW

**Comment by lex111** [comment]
@paroche thanks! ;)

**Comment by paroche** [comment]
No prob. Funny how it was just one extra letter forming an unrelated (as far as I know) word, but still almost worked the way it was.

**Comment by lex111** [comment]
Well, we all make mistakes.

**Comment by paroche** [comment]
Sure do. 
But it sort of **was** a cause as well as a case, even though I think "case" was intended.

**Comment by lex111** [comment]
I got you, but we are not native speakers, so such mistakes are typical for us.

**Comment by paroche** [comment]
Of course. You're doing great.

**Comment by iliakan** [comment]
That was actually a typo :/ thanks.

**Comment by paroche** [comment]
That's what I thought was most likely.

**Pull request merged**
