### PR TITLE
Javascript auto correct non px values to px values

### PR DESCRIPTION
**Pull request by Ooggle**
changed 08-styles-and-classes :
Javascript auto correct non px values to px values

### CODE REVIEW

**Comment by iliakan** [comment]
Check again. Assignment to `20` doesn't work (Chrome).

**Comment by Ooggle** [comment]
proof : https://streamable.com/vht4i

tested on Chrome, Firefox, Edge and Internet explorer.

**Comment by iliakan** [comment]
Your HTML is invalid, maybe that's the reason?

Do you also see `20px` here? 

https://plnkr.co/edit/27zWI3iypCxG7rivpisy?p=preview

**Comment by Ooggle** [comment]
Oh that very weird, i didn't see anything with Plunker (https://i.imgur.com/ons9Jgn.png).
But it's still work locally and remotely even with a valid HTML.

I'm confused.
Is that a browsers specific tolerance or something... ?

**Comment by iliakan** [comment]
Show me a valid HTML with that. (with DOCTYPE).

**Comment by Ooggle** [comment]
My bad i just modified a copy of the file and not the file itself, and obviously it's isn't working.
So thank you for having this topic and sorry for inconvenience.

**Pull request closed without merging**
