### PR TITLE
slightly improve clarity of Promise.all()

### PR DESCRIPTION
**Pull request by ZYinMD**

### CODE REVIEW

**Comment by iliakan** [comment]
Sorry, but the fix is wrong. When 1st promise dies, the `.all` dies too.

**Comment by ZYinMD** [comment]
Thanks, I'll submit a different fix to explain my self better.

**Comment by iliakan** [comment]
Sorry, I messed up. Your fix is perfectly correct.

**Comment by iliakan** [comment]
Thank you!

**Pull request merged**
